### ISSUE TITLE
Format python code and use linter

### ISSUE THREAD

**Issue by mapron** [Geomanti/PolyInPoly#2]
My personal preference is using flake8 for PEP8 compliance,  you can use any tool you comfortable with.
It's hard to read code which is not formatted according to PEP.

**Comment by Geomanti** [comment]
Thank you! Formated the code to read it more easily

**Comment by mapron** [comment]
well, `removedinsidepoints` is valid PEP8 style, but it probably must be `removed_inside_points` to be readable, and so one. python use snake_case style.

**Comment by Geomanti** [comment]
Fair.
